export const OBTENER_DENTISTAS = 'OBTENER_DENTISTAS';
export const OBTENER_DENTISTA = 'OBTENER_DENTISTA';
export const REGISTRAR_DENTISTA = 'REGISTRAR_DENTISTA';
export const MODIFICAR_DENTISTA = 'MODIFICAR_DENTISTA';
export const ELIMINAR_DENTISTA = 'ELIMINAR_DENTISTA';


export const paciente = {
    OBTENER_PACIENTES: 'OBTENER_PACIENTES',
    OBTENER_PACIENTE: 'OBTENER_PACIENTE',
    REGISTRAR_PACIENTE: 'REGISTRAR_PACIENTE',
    MODIFICAR_PACIENTE: 'MODIFICAR_PACIENTE',
    ELIMINAR_PACIENTE: 'ELIMINAR_PACIENTE',
}