export const OBTENER_DENTISTAS = 'OBTENER_DENTISTAS';
export const OBTENER_DENTISTA = 'OBTENER_DENTISTA';
export const REGISTRAR_DENTISTA = 'REGISTRAR_DENTISTA';
export const MODIFICAR_DENTISTA = 'MODIFICAR_DENTISTA';
export const ELIMINAR_DENTISTA = 'ELIMINAR_DENTISTA';
